### ISSUE TITLE
Still getting 8 second cooldown on Venture's secondary fire

### ISSUE THREAD

**Issue by vwade** [6v6-Adjustments/6v6-adjustments-fork#36]
Venture cooldown is inconsistent with desired change on live build.

Expected:
- Drill Dash on cooldown is 6 seconds

Actual:
- Drill Dash on cooldown is 8 seconds.

Proposal:
- Constrain cooldown to 6 seconds if greater than 6 seconds.

**Comment by MaxwellJung** [comment]
Looks like the cooldown slider didn't register in live version for some reason.

Fix is to disable and reenable drill dash in venture settings to register the settings
