### ISSUE TITLE
echo focusing beam damage inaccurate

### ISSUE THREAD

**Issue by MaxwellJung** [6v6-Adjustments/6v6-adjustments-fork#39]
echo global damage is scaled by a factor of 170/180 to nerf sticky bombs, however, only the primary fire and melee damage is corrected by workshop.

**Comment by ieToastie** [comment]
Was initially concerned about this due to script load related reasons, but anti-crash seems to only trigger sparingly and is doing its job well. I'll add a rule in the future that corrects this.
