### ISSUE TITLE
Ramattra balance changes

### ISSUE THREAD

**Issue by ieToastie** [6v6-Adjustments/6v6-adjustments-fork#5]
Remove the single-use restriction for Block in Nemesis Form and replace it with a 3 second cooldown
- The cooldown for Block should be 0 while in Annihilation

**Comment by MaxwellJung** [comment]
do you have to make custom cooldown like zarya bubbles?

**Comment by ieToastie** [comment]
I messed with trying to put the ability on cooldown naturally, but it seems Block doesn't go on cooldown under any circumstances, so we'll need to build a new workshop cooldown to get this working (similar to Zarya like you said)
