### ISSUE TITLE
Moira receiving unintended health regeneration

### ISSUE THREAD

**Issue by ieToastie** [6v6-Adjustments/6v6-adjustments-fork#54]
Biotic orb, in both its forms, allows moira to receive self healing while it is active regardless if it is directly healing moira or not. This causes moira to receive much more self healing than intended across an entire game, suggest using damage ticks method on moira specifically to prevent this

**Comment by MaxwellJung** [comment]
I thought moira already used damage tick method for all self healing but i'll check

**Comment by MaxwellJung** [comment]
I can't replicate the bug in dev build because moira already uses damage ticks for regen passive suppression

My guess is that moira went into fade on one of the damage ticks and briefly triggered regen passive.

Closing issue for now but reopen if not fixed
